log:
  - name: "master"
    level: debug
    format: "%d%T%p%T%t%T%F%T%f%T%l%T%m%n"
    appenders: 
      - level: info
        path: null
        type: StdLogAppender
        format: "%d%T%p%T%t%T%F%T%f%T%l%T%m%n"
      - level: info
        path: /home/luo/cplus/sylar/loglist/log.txt
        type: FileLogAppender
        format: "%d%T%p%T%t%T%F%T%f%T%l%T%m%n"
  # - name: system
  #   level: debug
  #   formater: "%d%T%p%T%t%T%F%T%f%T%l%T%m%n"
  #   appender: 
