logs:
  - name: "master"
    level: info
    format: "%d%T%lN%T%p%T%t%T%tN%T%F%T%f%T%l%T%m%n"
    appenders: 
      - level: info
        path: null
        type: StdLogAppender
        format: null
      - level: info
        path: log.txt
        type: FileLogAppender
        format: "%d%T%lN%T%p%T%t%T%tN%T%F%T%f%T%l%T%m%n"
coroutine:
  stacksize: 131072
